### ISSUE TITLE
Can't find the .pdf file of your report

### ISSUE THREAD

**Issue by botsbuzz** [Schlegen/Microgrid-Manager#2]
Hi,

your project seems to be really interesting. I'd like to have more details about it, but I can't find your pdf report.

Could you help me?

Best,

Stefano

**Comment by Schlegen** [comment]
Hi,

Sure, I have just uploaded it. You may notice that it is in French. I hope it wont be a problem for you. 

Good reading, 

Nicolas

**Comment by botsbuzz** [comment]
Thank you so much Nicolas!
