### ISSUE TITLE
Help with data for simulation

### ISSUE THREAD

**Issue by botsbuzz** [Schlegen/Microgrid-Manager#3]
Hi Nicolas,

could you help me to understand the file customers1213.txt? I need to understand how I have to prepare the data for simulation.

Best,

Stefano

**Comment by Schlegen** [comment]
Hello, 

I invite you to read the function load_data_frame in tools.py. Here is an explanation of the file :
Each line corresponds to a customer(a microgrid) :

**Comment by Schlegen** [comment]
Hello,

I invite you to read the function `load_data_frame` in `tools.py`. Here is an explanation of the `customer1213.txt` file :
Each line corresponds to a customer (a microgrid) : The first number of the line is the id of the microgrid, the second is the length of the mesure, let's call it `n`. Then, the `n` values after correspond to the generation data (GG) and the `n` values that come after are the consumption data (GC). The separators are spaces. In my case, each line contains 1 year of data.

**Comment by botsbuzz** [comment]
Thank you so much for your help, Nicolas!
